---
services:
  unifi:
    image: ghcr.io/ilmax/unifi-docker:latest
    init: true
    container_name: unifi
    environment:
      PKGURL: ""
      UNIFI_STDOUT: "true"
      TZ: Etc/UTC
    user: unifi
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/manage/account/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    volumes:
      - ./.data/unifi:/unifi:Z
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
